---
- name: Copy the directory to remote machine 
  hosts: all
  vars_files:
    - vars/commonvars.yml
    - vars/icamvars.yml
 
  tasks:
 
  - name: Set variable dest_image to "{{ default_image }}"
    set_fact:
      dest_image: "{{default_image}}"



