---
- name: Copy the directory to remote machine 
  hosts: all
  connection: local
  user: root
  gather_facts: no
  tasks:
  - shell: echo 'test'
    register: foo
  - debug: msg="the echo was {{ foo.stdout }}"
